### PR TITLE
Relevant message

### LINKED ISSUE #282: Improve the show password method in login, sign-up, and forget password page
Remove the show password checkbox and add icons in the input fields.
Do this on the login, sign-up, and forget password page.

image

### PR DESCRIPTION
**Pull request by yuhang0627**
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
I had change all the show password button to the bi eye logo make it looking more nice.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x ] I have mentioned related issue number in PR description.
- [ x] I have added screenshots and related demo links of my changes..
- [ x] The title of my pull request is a short description of the requested changes.
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)
forgetPass_page
login_page
signup_page

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@yuhang0627 you have compressed the size of the input field.

It should be of the same size like other fields as it was before.

Also, try to shift the Eye icon inside the input tab.

**Comment by QAZIMAAZARSHAD** [comment]
And fetch upstream also your repo is 14 commits behind.

**Comment by yuhang0627** [comment]
Like these okay?

forgetPass
login
signup

**Comment by QAZIMAAZARSHAD** [comment]
Yes looks better.

But I think you have also modified the buttons.

Don't change anything else.

**Comment by QAZIMAAZARSHAD** [comment]
Reset the buttons.

Fetch upstream.

And when you are done share a deployment link so I can review your changes.

**Comment by yuhang0627** [comment]
> Reset the buttons.
> 
> Fetch upstream.
> 
> And when you are done share a deployment link so I can review your changes.

I had reset and fetch upstream.
How I share a deployment link? Newbie here sorry.

**Comment by QAZIMAAZARSHAD** [comment]
Host your website on GitHub Pages, Netlify, repl.it or any other platform then share the link.

**Comment by yuhang0627** [comment]
> Host your website on GitHub Pages, Netlify, repl.it or any other platform then share the link.

This?
https://yuhang0627.github.io/Voters-Registration-Portal/

**Comment by yuhang0627** [comment]
> Host your website on GitHub Pages, Netlify, repl.it or any other platform then share the link.

This？
https://yuhang0627.github.io/Voters-Registration-Portal/

**Comment by QAZIMAAZARSHAD** [comment]
> > Host your website on GitHub Pages, Netlify, repl.it or any other platform then share the link.
> 
> This？
> https://yuhang0627.github.io/Voters-Registration-Portal/

Yes.

**Comment by QAZIMAAZARSHAD** [comment]
@yuhang0627 the confirm password icon is not working in forget pass and signup page.

And why you closed PR?

Make another one.

**Pull request closed without merging**
