### PR TITLE
Add mailto link in footer and correct hover effect on help button

### LINKED ISSUE #382: Add mailto link in footer and correct hover effect on help button
image

Add mailto link to the email. 
Remove the underline when hovering on the help desk button.
Apply the same hovering on the email button as in the hep desk button.
Also, add a similar hover effect on the toll-free button.

Make sure all the three buttons call, email, and the help desk should be of the same size.

### PR DESCRIPTION
**Pull request by nagybnc**
#### Describe the changes you've made
 
Add tel link to the telephone.
Add mailto link to the email.
Remove the underline when hovering on the help desk button.
All three buttons (Call, Email, Help Desk) use same style.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshot 2021-07-18 at 21 47 20

#### Checklist
- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by nlok5923** [comment]
@nagybnc code looks good just deploy your change and provide a test deployment link to test your changes once done will merge it.

**Comment by nagybnc** [comment]
@nlok5923 https://nagybnc.github.io/Voters-Registration-Portal

**Comment by QAZIMAAZARSHAD** [comment]
@nagybnc the website has been updated.

Your repo is 9 commits behind.
Fetch upstream.

**Comment by QAZIMAAZARSHAD** [comment]
Check the responsiveness as well.

Your changes have shifted the content in the footer to the extreme right.
image

**Comment by QAZIMAAZARSHAD** [comment]
And the height of the email button is slightly larger, try to make it similar to other buttons.

**Comment by QAZIMAAZARSHAD** [comment]
@nagybnc any updates?

**Comment by nagybnc** [comment]
@QAZIMAAZARSHAD I will do it today

**Comment by nagybnc** [comment]
I have an issue with my computer, so I need some extra time :/

**Comment by QAZIMAAZARSHAD** [comment]
> I have an issue with my computer, so I need some extra time :/

Fine.

**Comment by nagybnc** [comment]
@QAZIMAAZARSHAD Done. Sorry for the delay.
Screenshot 2021-07-27 at 21 43 44

**Review by nlok5923 — APPROVED** [review]
Code LGTM !! @QAZIMAAZARSHAD i think we can merge this pr.

**Pull request merged**
