### PR TITLE
Toggle button

### PR DESCRIPTION
**Pull request by nik464**
#### Fixes #(issue number)
 
#303 

#### Describe the changes you've made
I have changed the toggle button position from top to bottom left in all pages.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
I have resolve all merge conflicts and added at bottom of all pages.

#### Additional context (OPTIONAL)
image
You can see the button

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@nik464 mention issue number.

Fill description and title of PR properly.

**Comment by nik464** [comment]
> @nik464 mention issue number.
> 
> Fill description and title of PR properly.

Ya , it was sent by mistake without editing. But now  I have resolved merge conflicts in index.html. You can easily merge the file and accept pull request. Issue no is 303.

**Comment by nik464** [comment]
0 conflicts and can be easily merged and the task 303 is completed.

**Comment by QAZIMAAZARSHAD** [comment]
No not completed.

Do this on every page.
Align it to the bottom left corner, in the screenshot it is not too much left.

**Comment by QAZIMAAZARSHAD** [comment]
And share website link after changes.

**Comment by nik464** [comment]
ok

**Comment by nik464** [comment]
I have added at bottom left of every page: index, home, login,signup, help,feedbackform etc. Now you can merge.

**Comment by nik464** [comment]
http://127.0.0.1:5501/index.html

**Comment by nlok5923** [comment]
> http://127.0.0.1:5501/index.html

@nik464 this is not correct you need to deploy it any static deployment service like netlify or github pages also can you please let me know why did you changed the color of toggle button ?
image

**Comment by nik464** [comment]
ok so i have to host the website at cloud platform?  I actually changed the color because it was not matching with background. At some places background is complete black and some it is grey.

**Comment by nik464** [comment]
https://focused-northcutt-9e712d.netlify.app/

**Comment by QAZIMAAZARSHAD** [comment]
Not working in few pages.

Also, you have added an unnecessary margin below the header on the index page.
Also the color is still red.

**Comment by nik464** [comment]
i have removed scrollbars. They were already present in your document, but I have removed them. 

Also the button has been restored to original colours which were asked. Ball is white and background is black which is original one.  

Third thing, all of them are now responsive. Index page unnecessary margin has been removed which was initially below the header
Now, please add merge requests. It has become lengthy and hectic..

**Comment by nik464** [comment]
https://focused-northcutt-9e712d.netlify.app/.

**Comment by QAZIMAAZARSHAD** [comment]
Why have you removed the scroll bar from all the pages?

And horizontal scroll bar is still there on the help page.

**Comment by QAZIMAAZARSHAD** [comment]
> Not working in few pages.
> 
> Also, you have added an unnecessary margin below the header on the index page.
> You have added horizontal scroll bar in help page.
> Also the color is still red.

I just meant to remove the horizontal scroll bar from the help page.

**Comment by nik464** [comment]
ok i will restore vertical bars and remove horizontal bar. Everything else if fine?

-

**Comment by nik464** [comment]
finally done all the work.  hope you are happy with website change. https://focused-northcutt-9e712d.netlify.app/

**Comment by QAZIMAAZARSHAD** [comment]
https://focused-northcutt-9e712d.netlify.app/help.html

Check the help page.

Correct the spacing. 
Check arrangement within the box.

**Comment by nik464** [comment]
Now i have change help.html by giving spacing. Also everything is arranged properly with respect to your original document page. Now if you want you can merge.

**Pull request merged**
