### PR TITLE
Update Home.html

### LINKED ISSUE #274: Respective legislative and parliamentary constituency should display automatically as soon as district is selected
## Additional context
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by Mangesh1511**
Fixes #274

Done with assembly for each district and will be doing more 2-3 states further and found populate function repititive so removed 2 redundant of them.

Here's the link with updated file
[](https://62f087fab465cf08ab0867dc--starlit-malasada-f2cae6.netlify.app/)

https://62f087fab465cf08ab0867dc--starlit-malasada-f2cae6.netlify.app/

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Mangesh1511 Not working!!!

image

**Comment by Mangesh1511** [comment]
I have done Only with Maharashtra assembly and will do all in one or 2 days for sure

**Comment by Mangesh1511** [comment]
For now u can check any district in maharashtra

**Comment by QAZIMAAZARSHAD** [comment]
Fine,

But this looks like a lot of hard work, I suggest you should search for any API's for the task.

**Comment by Mangesh1511** [comment]
Yes now I visited one site of elections and there was no such thing I will
try by api now

**Comment by QAZIMAAZARSHAD** [comment]
I'll merge this PR soon.

**Pull request merged**
