### PR TITLE
#332

### PR DESCRIPTION
**Pull request by stellashank**
Flip Logo Corrected

#### Issue Number #332

### CODE REVIEW

**Comment by stellashank** [comment]
Do you confirm sir?!

**Comment by QAZIMAAZARSHAD** [comment]
> Do you confirm sir?!

Is this the change shown in the image you have done?

**Comment by QAZIMAAZARSHAD** [comment]
Logo in all pages should be like this https://qazimaazarshad.github.io/Voters-Registration-Portal/help.html.

**Comment by stellashank** [comment]
The logo in help page is flipping when hovered on.

**Comment by QAZIMAAZARSHAD** [comment]
> The logo in help page is flipping when hovered on.

Yesss, but not in other pages that's the issue.

Make all pages logo similar to help page.

**Comment by stellashank** [comment]
The flip logo is working fine in all pages.
Can u share the snap for issue in Base Repo

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (22)
Screenshot (24)


The red circle indicates the wrong output on hover.
The blue circle indicates the correct output on hover.

**Comment by QAZIMAAZARSHAD** [comment]
@stellashank do only necessary changes.

The problem is in style.css.

Make new PR.

**Comment by stellashank** [comment]
#30 Validation for Password Email Phone no. done in second commit.
can u confirm sir?

**Comment by QAZIMAAZARSHAD** [comment]
> #30 Validation for Password Email Phone no. done in second commit.
> can u confirm sir?

@stellashank make separate PR's for separate issues and mention related issue numbers.

**Comment by QAZIMAAZARSHAD** [comment]
And issue number 30 is for the main form not sign-up page.

**Pull request closed without merging**
