### PR TITLE
added website links in the footer section

### PR DESCRIPTION
**Pull request by Namangujral1**
Issue number: #248
 Generated a new issue
#### Describe the changes you've made
I have seen the home page of the website and I find some bugs in the footer section. Like the mentioned websites are not be viewed as there hyperlinks are not provided in that section.
Sorry I forgot to mention myself in the contributor list in the readme file.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Always mention the issue number in PR description.

Edit it.

**Comment by QAZIMAAZARSHAD** [comment]
Always mention the issue number in PR description.

Edit it.

**Comment by Namangujral1** [comment]
> Always mention the issue number in PR description.
> 
> Edit it.

okkk, wait i will edit it

**Comment by QAZIMAAZARSHAD** [comment]
Like this #244.

**Comment by QAZIMAAZARSHAD** [comment]
And 244 is the PR number, not the issue number.

I don't think any such issue was ever open.

**Comment by QAZIMAAZARSHAD** [comment]
Before making any PR, first, get yourself assigned to that particular issue.

**Comment by QAZIMAAZARSHAD** [comment]
Open an issue to add links in the footer, ping me to assign you that issue.

Also, you have added links only in home.html, add it in every page, login, help, forget password, signup.

**Comment by Namangujral1** [comment]
> Open an issue to add links in the footer, ping me to assign you that issue.
> 
> Also, you have added links only in home.html, add it in every page, login, help, forget password, signup.

Yeah such type of issue is not there, I have created it on my own and doesn't know what to mention in the issue number.
Ok I will add it in every page, as of now, I have added it in only in home.html .

**Comment by QAZIMAAZARSHAD** [comment]
> > Open an issue to add links in the footer, ping me to assign you that issue.
> > Also, you have added links only in home.html, add it in every page, login, help, forget password, signup.
> 
> Yeah such type of issue is not there, I have created it on my own and doesn't know what to mention in the issue number.
> Ok I will add it in every page, as of now, I have added it in only in home.html .

Also, open the issue.

**Pull request closed without merging**
