### PR TITLE
Made Website completely responsive!

### LINKED ISSUE #44: Adding Favicon
Favicon is missing in the website

### LINKED ISSUE #45: correcting the alignment and spacing between the fields
The alignment is not that good. I as a participant of LGMSOC would like to would on it and try making it aligned.

### PR DESCRIPTION
**Pull request by Kartikey0205**
#### Issue Number #11 
fixes #44 
fixes #45 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
* `I had made changes in the HTML , CSS file to make it responsive completely for any device and also made navbar fixed `
* `uses some media queries too!`
* `Also I had added a Java script file which simply does the work to increase / decrease font size when somebody click on A+ or A- button`
* `Used Bootstrap CDN and by rewriting (or say editing )the code I (Kartikey Dubey) made this Project Responsive under LGM-SOC'21 `
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
* `Although I had added the favicon but the link which github gives us under this favicon is not showing, someone please resolve this`
* `In addition with this i had made 2 button (reset and submit button ) and style their color with white but I just forget to edit the color of keyboard icon due to which it also be in white color (which is quite visible) , ofcourse I can solve this but lets someone else try  this `

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

`If you want to test my website then click below`
[Voter's registration Portal](https://kartikey0205.github.io/Voters-Registration-Portal/)

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)`Lgm-soc'21`

### Large Screen Preview
<br>

Large Screen Preview
<br>
### Mobile Screen Preview
<br>

Mobile Preview
<br>
### iPad Screen Preview
<br>

iPad screen Preview

###   Kartikey Dubey 
@kartikey0205

### CODE REVIEW

**Review by shivshankar9 — APPROVED** [review]
Great work!!

**Comment by QAZIMAAZARSHAD** [comment]
@Kartikey0205 you have to make separate PR's for separate issues.

Also, you can make PR for only those issues for which you are assigned. 
You have mentioned issue 44 which is already closed and issue 45 which has not been acknowledged yet.

Your design for mobile view and tab view is perfectly fine but you have also done some changes in the desktop view as well which is not fine.

Close this PR.
And change the desktop view back to the previous design.
Then make PR for issue number 11 only.

**Comment by Kartikey0205** [comment]
@QAZIMAAZARSHAD  you ask me to set previous design for desktop view as well right ? 
So it means you don't need sticky navbar and also you need big fonts in navbar ?

Am I right ? 
or not if not then 
please tell me what does you need in the desktop view because as I see in desktop view it seems properly.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD you ask me to set previous design for desktop view as well right ?
> So it means you don't need sticky navbar and also you need big fonts in navbar ?
> 
> Am I right ?
> or not if not then
> please tell me what does you need in the desktop view because as I see in desktop view it seems properly.

Yes, no need for a sticky navbar also your navbar is very small.
The previous font size was better and text alignment was better.
The previous desktop view was fine.

Your designs for mobile view and tab view were fine but don't make any changes in the desktop view.

**Pull request closed without merging**
