### PR TITLE
Help section is added in footer

### PR DESCRIPTION
**Pull request by royalleads15**
#32 
fixes #

#### Describe the changes you've made
help section is added in footer

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
N/A

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

### CODE REVIEW

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD kindly review thi PR and let me know weather I have to do further modifications Or it is right.

**Comment by QAZIMAAZARSHAD** [comment]
I'll review it soon.
My 3 projects are in LGMSOC'21 and I have received more than 150 GitHub notifications today.
It won't be possible for me to review it today. Till then have patience.

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD please review help section.

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD I have also added dark and light mode toogle . please review it .

**Comment by QAZIMAAZARSHAD** [comment]
Resolve the conflicts first.

Try to make new PR. First, fetch upstream and update your repo.

**Pull request closed without merging**
