### PR TITLE
Changed some code to provide better responsiveness to the page

### LINKED ISSUE #423: Check the responsiveness of login page in mobile view

### PR DESCRIPTION
**Pull request by RiyaGupta89**
# Fixes #423 

## Describe the changes you've made
I have majorly changed in the width of the main container in the mobile view which results in less space on the left and right and giving more space to the content inside.

## Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)

login-responsive

login-responsive1

#### Test plan (OPTIONAL)
I will added comment outside my code therefore its easy for anyone to follow.

#### Checklist

- [✔️] I have mentioned related issue number in PR description.
- [✔️] I have added screenshots of my changes..
- [✔️] The title of my pull request is a short description of the requested changes.
- [✔️] My code follows the code style of this project.
- [✔️] Lets Grow More

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share your website link for review.

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD 
https://quizzical-goldberg-9e99a2.netlify.app/login.html 
I don't know why the code changes are not visible here.

**Comment by QAZIMAAZARSHAD** [comment]
image

@RiyaGupta89 what changes have you made?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD
> https://quizzical-goldberg-9e99a2.netlify.app/login.html
> I don't know why the code changes are not visible here.

Oooo.


Host on GitHub pages then.

**Comment by nlok5923** [comment]
> @QAZIMAAZARSHAD
> https://quizzical-goldberg-9e99a2.netlify.app/login.html
> I don't know why the code changes are not visible here.

while deploy to netlify you need to specify which branch you need to deploy so please select correct branch which contains changes done by you.

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 if PR is merged after today then it will not be considered for LGM-SoC.

**Pull request closed without merging**
