### PR TITLE
Responsiveness feature checked of submitted file | Image fixed | Line edited 

### PR DESCRIPTION
**Pull request by shreya-madhwal**
Fixes #5
Issue-Fix the image in submitted.html also check the responsiveness of page
 
The changes I've made:
1. Image got fixed.
2. Added few lines of code for responsiveness of the page in submitted.html and submitted.css
3. Edited the line as mentioned in the issue.

Any unusual behaviour in the code:
NA

 Additional context :
image

Done under lgmsoc'21

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

**Comment by shreya-madhwal** [comment]
> Share the website link so I can review your changes.

file:///C:/Users/com/Desktop/lgmsoc'21/Voters-Registration-Portal/submitted.html

Here it is sir.

**Comment by shreya-madhwal** [comment]
> Share the website link so I can review your changes.

file:///C:/Users/com/Desktop/lgmsoc'21/Voters-Registration-Portal/submitted.html

**Comment by shreya-madhwal** [comment]
https://github.com/shreya-madhwal/Voters-Registration-Portal/blob/master/submitted.html

This is the link sir.

**Comment by QAZIMAAZARSHAD** [comment]
No this not a website link.

Host your website somewhere like GitHub pages or repl.it then share.

**Comment by QAZIMAAZARSHAD** [comment]
> https://github.com/shreya-madhwal/Voters-Registration-Portal/blob/master/submitted.html
> 
> This is the link sir.

Like this 
https://qazimaazarshad.github.io/Voters-Registration-Portal/

**Comment by shreya-madhwal** [comment]
> > https://github.com/shreya-madhwal/Voters-Registration-Portal/blob/master/submitted.html
> > This is the link sir.
> 
> Like this
> https://qazimaazarshad.github.io/Voters-Registration-Portal/

okk sir got it wait lemme send it.

**Comment by shreya-madhwal** [comment]
https://shreya-madhwal.github.io/Voters-Registration-Portal/

**Comment by QAZIMAAZARSHAD** [comment]
@shreya-madhwal you have mentioned the wrong issue number.

This is issue #320.

**Comment by QAZIMAAZARSHAD** [comment]
Also, your repo is not updated.

Always fetch upstream before working on any issue, PR is merged only because the submitted page was even with your repo otherwise it would have shown conflicts.

**Comment by shreya-madhwal** [comment]
Ok got it. But there's one doubt when u assigned me this issue it was having level1 tag but now here it is showing level0 could u pls help me in this.

**Comment by QAZIMAAZARSHAD** [comment]
> Ok got it. But there's one doubt when u assigned me this issue it was having level1 tag but now here it is showing level0 could u pls help me in this.

Oo this is a mistake.
I was adding label 1 but somehow I clicked level 0 I think.

**Comment by shreya-madhwal** [comment]
> > Ok got it. But there's one doubt when u assigned me this issue it was having level1 tag but now here it is showing level0 could u pls help me in this.
> 
> Oo this is a mistake.
> I was adding label 1 but somehow I clicked level 0 I think.

Thanks @QAZIMAAZARSHAD for your help and support.

**Pull request merged**
