### PR TITLE
modified the css of login page

### PR DESCRIPTION
**Pull request by Swarga-codes**
ISSUE #203 
fixes #

Description:
I have made some changes with the CSS , i.e CSS of the login form to make it look better than before added a background image in that particular section and added a blur effect to it (the form container) which made it look far better than before and also made changes to the form like included placeholders and worked with the positioning of its contents and changed the button colors to green and orange which suits with this type of website. Just made this noticable changes with the login form.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA.

#### Additional context (OPTIONAL)
Screenshot (171)

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?
One can 
#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Nice.

Resolve the conflicts.

And do the same for signup.html and forgetpassword.html.

**Comment by Swarga-codes** [comment]
> Nice.
> 
> Resolve the conflicts.
> 
> And do the same for signup.html and forgetpassword.html.

Sir , can you please tell me how do I resolve those conflicts? , since I'm new to open source contributions.

**Comment by QAZIMAAZARSHAD** [comment]
> > Nice.
> > Resolve the conflicts.
> > And do the same for signup.html and forgetpassword.html.
> 
> Sir , can you please tell me how do I resolve those conflicts? , since I'm new to open source contributions.

It is showing conflicts because your repo is not updated with main.

Fetch Upstream to resolve.

**Comment by QAZIMAAZARSHAD** [comment]
Do the necessary changes then make a new PR.

**Pull request closed without merging**
