### PR TITLE
forget password page

### LINKED ISSUE #191: Forget password page
## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

### PR DESCRIPTION
**Pull request by kumarishalini6**
#### Issue Number
fixes #191 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by kumarishalini6** [comment]
Hey you forget to add level

**Comment by QAZIMAAZARSHAD** [comment]
Didn't forget, just checking you work.

GitHub taking time to load says forget.html not found.

**Comment by QAZIMAAZARSHAD** [comment]
https://qazimaazarshad.github.io/Voters-Registration-Portal/

Check is forget page visible?

**Comment by kumarishalini6** [comment]
But I have just take upstream and its shows forget.html

**Comment by kumarishalini6** [comment]
> https://qazimaazarshad.github.io/Voters-Registration-Portal/
> 
> Check is forget page visible?

Yes I can see

**Pull request merged**
