### PR TITLE
feat:changed the favicon image and added a dynamic favicon and title

### PR DESCRIPTION
**Pull request by codingninja11**
https://user-images.githubusercontent.com/64359203/124150874-9b072200-daaf-11eb-9b8f-b423e366bd47.mp4

### CODE REVIEW

**Review by QAZIMAAZARSHAD — CHANGES_REQUESTED** [review]
@codingninja11 make changes in forget pass and form correction page as well,

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts also.

**Comment by codingninja11** [comment]
> @codingninja11 make changes in forget pass and form correction page as well,

I made the required changes please check it now. @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@codingninja11 iit s working only in index.html.

**Comment by codingninja11** [comment]
> @codingninja11 iit s working only in index.html.

I made the changes should I make a new PR?

**Comment by QAZIMAAZARSHAD** [comment]
Yes make a new PR.

**Pull request merged**
