### PR TITLE
Designed footer

### LINKED ISSUE #216: Improve footer design
Design footer like this 
image

### PR DESCRIPTION
**Pull request by RiyaGupta89**
#### Issue Number
fixes #216

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Add the footer to help page as well.

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD First please accept my current PR, as their is a conflict that needs to be solved. My fork repo was one commit behind the original repo therefore I fetched and merged and all my code vanished from there. I have to write all that code again. Please merge the current PR into main and I will footer in the help page right away.

**Comment by QAZIMAAZARSHAD** [comment]
Okk, create new PR for the help page footer, Then I will add label.

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 your footer has disturbed the entire mobile view.

Check responsiveness as well for all pages in your next PR.

**Comment by QAZIMAAZARSHAD** [comment]
Copyright © 2021Qazi Maaz Arshad

There is now space between 2021 and Qazi, correct this as well.

**Comment by QAZIMAAZARSHAD** [comment]
help[@]nationalvoterportal[.]gov[.]in

Correct this line as well.

**Comment by QAZIMAAZARSHAD** [comment]
I will raise the level of the issue if you did everything correctly.

**Comment by RiyaGupta89** [comment]
Did everything, please have a look.

**Pull request merged**
