### PR TITLE
Improved functionality of print function

### LINKED ISSUE #226: Improve print form functionality
Print function prints the entire web page including header, footer, captcha, etc.

It should work properly and only the submitted form should be printed.

### PR DESCRIPTION
**Pull request by RiyaGupta89**
#### Issue Number
fixes #226
 Please have a look. My PR resolves all of the issues.

### CODE REVIEW

**Comment by nlok5923** [comment]
@RiyaGupta89  thanks for pr can you please provide a static deployment at netlify/gh-pages to test your changes.

**Comment by RiyaGupta89** [comment]
@nlok5923 Here it is,  https://riyagupta89.github.io/Voters-Registration-Portal/

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 same issue in your PR.

Submitted details in the form are not getting printed.

One improvement also, unnecessary details are not printing in mobile view.


Try again.

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD shall i revert this commit concerning your feedback to this pr.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD shall i revert this commit concerning your feedback to this pr.

No,

There were few improvements. I merged it on purpose.

**Comment by QAZIMAAZARSHAD** [comment]
@nlok5923 don't merge or revert any PRs.

You can close PR if you think something's wrong.

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD Look the details are getting printed. I've not filled all the details, I've filled few of them and all those are getting printed. Have a look.
Screenshot_2021-06-22-21-57-07-281_com android printspooler

**Comment by QAZIMAAZARSHAD** [comment]
Tried again thrice.

Not working !!!!!!

Nothing printing.

**Pull request merged**
