### PR TITLE
Add a Help Section page

### LINKED ISSUE #32: Add help section
Help section must be added in header or footer so that if anyone find difficulty in registration process he/she can acess it .

### PR DESCRIPTION
**Pull request by harshita9621**
#### Issue Number
fixes #32

#### Describe the changes you've made

I added a help section page and add to a main page in a footer section and in help section i create a form in which peoples are write there query and ask for help and I add a FAQ section also in help desk and it will be updated if we done some research what are the common queries. So that my task please review it and give the feedback and thank you for assigned me that issue.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshot (54)

Screenshot (55)

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by harshita9621** [comment]
@QAZIMAAZARSHAD Please have a look on this PR

**Comment by QAZIMAAZARSHAD** [comment]
Will review soon.

**Comment by harshita9621** [comment]
I resolve the conflict ,please review

**Comment by QAZIMAAZARSHAD** [comment]
Not resolved

**Comment by QAZIMAAZARSHAD** [comment]
Resove conflicts.

First update your repo then push changes.

**Pull request closed without merging**
