### PR TITLE
Dark and light mode toogle switch

### LINKED ISSUE #28: Add dark/light mode to website
Dark and light mode must be added in portal so that user can access it as he/she wants.

### PR DESCRIPTION
**Pull request by royalleads15**
#28 
fixes #28 

#### Describe the changes you've made
Dark and light mode toggle switch is added by clicking on which a user can switch light mode to dark mode.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
N/A

#### Additional context (OPTIONAL)
Light Mode
dark1
DARK mode
dark2

#### Test plan (OPTIONAL)
Click on that toggle button to change theme .

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Do changes for hindihome.html as well.

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD I have added dark mode in home_hindi.html . Please review it .

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD  I have resolved the conflicts .

**Comment by QAZIMAAZARSHAD** [comment]
The website has been updated.

Review your changes.

Update repo then make a new PR.

**Pull request closed without merging**
