### PR TITLE
Updated Footer

### LINKED ISSUE #41: Footer Copyright Year
Hey @QAZIMAAZARSHAD 
I would like to change the footer year and it will take according to the correct year.
Need not change every time.
Thanks

### PR DESCRIPTION
**Pull request by Shaishav0507**
#### Issue Number #41 
fixes #41 
Thanks for giving me this opportunity to work on this project.

#### Describe the changes you've made
Updated footer year in 3 files.
Now no need to change everytime.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Changes look fine.

But resolve conflicts.

**Comment by Shaishav0507** [comment]
Should I remove that part ?
To resolve the conflict

**Comment by Shaishav0507** [comment]
Done please check it.

**Comment by QAZIMAAZARSHAD** [comment]
> Done please check it.

Not done,

Why you deleted the footer from home.html and hindihome.html.

Do the changes.

**Comment by Shaishav0507** [comment]
What changes I need to do

**Comment by QAZIMAAZARSHAD** [comment]
> What changes I need to do

Review your changes once.

You have deleted the footer in the home.html and hundihome.html, you were supposed to update the footer as you did in index.html not delete them.

**Comment by Shaishav0507** [comment]
Have done it.
Please check it
If anything needs to be done

**Comment by Shaishav0507** [comment]
Is it correct ?

**Comment by QAZIMAAZARSHAD** [comment]
Not correct.

You have deleted the help bar from the footer.


First update your repo completely then make only the necessary changes.

**Comment by Shaishav0507** [comment]
Ok I will make new PR.

**Pull request closed without merging**
