### PR TITLE
Address of regional office should display on selecting every state

### LINKED ISSUE #383: Address of regional office should display on selecting every state
image

Screenshot (71)

Set default address of Delhi.
No need to add all the states, only existing states in the list are fine.
The address of every state should be different.

Sample address:

NVP Regional Office, Delhi
Ground Floor, Pragati Maidan Metro Station, 
Pragati Maidan, New Delhi-110001

Update every footer.

### PR DESCRIPTION
**Pull request by RiyaGupta89**
#### Describe the changes you've made
I have added the new address and it changes as the user selects some other city, the address gets changed. I have also added the default as delhi.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)

https://user-images.githubusercontent.com/72425181/126258366-09d34629-2147-497c-907b-ea90c802bee2.mp4

#### Test plan (OPTIONAL)
I have provided a video, please have a look.

### CODE REVIEW

**Review by nlok5923 — APPROVED** [review]
Code looks good to me !!

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 under LGMSoC or DCP?

**Comment by RiyaGupta89** [comment]
> @RiyaGupta89 under LGMSoC or DCP?

Lgmsoc.

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 same address is not possible in every city.

Make every address of city different.


Make one more PR.

**Pull request merged**
