### PR TITLE
Improved design Of LoginPage,ForgetPass Page and SignUp Page

### PR DESCRIPTION
**Pull request by skpandey885**
Issue No. #279 

Changes Made:
1. Css Of Login, Forget Password  & Signup Page Changed.
2. New Font Added.
3. Responsiveness Improved.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 I have reverted your PR because there is a bug and I thought your PR created this.

image

Make PR again.

Also, I am trying to understand how this happened because last I checked everything was fine. If you find the solution make PR.

**Comment by QAZIMAAZARSHAD** [comment]
@nlok5923 have you merged any PR that caused this or have done any changes?

Resolve this if you find bug.

**Comment by skpandey885** [comment]
> @skpandey885 I have reverted your PR because there is a bug and I thought your PR created this.
> 
> image
> 
> Make PR again.
> 
> Also, I am trying to understand how this happened because last I checked everything was fine. If you find the solution make PR.

Okey Bhaiya! But as per I know This Bug is not occurred Because Of Me! So What Do I do Right Now?

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 check if the header of the home and help page is fine then include it in your PR.

**Comment by QAZIMAAZARSHAD** [comment]
> > @skpandey885 I have reverted your PR because there is a bug and I thought your PR created this.
> > image
> > Make PR again.
> > Also, I am trying to understand how this happened because last I checked everything was fine. If you find the solution make PR.
> 
> Okey Bhaiya! But as per I know This Bug is not occurred Because Of Me Because I Did Changes Only In Three HTML Files! So What should I do Right Now?

Yaa, I know your PR is fine, make PR again.

**Comment by skpandey885** [comment]
> > > @skpandey885 I have reverted your PR because there is a bug and I thought your PR created this.
> > > image
> > > Make PR again.
> > > Also, I am trying to understand how this happened because last I checked everything was fine. If you find the solution make PR.
> > 
> > 
> > Okey Bhaiya! But as I know This Bug has not occurred Because Of Me Because I Did Changes Only In Three HTML Files! So What should I do Right Now?
> 
> Yaa, I know your PR is fine, make PR again.

I am Unable To Generate PR! It Is Showing "Nothing To Compare"

**Comment by QAZIMAAZARSHAD** [comment]
Try fetch upstrem

**Comment by skpandey885** [comment]
> Try fetch upstream

It is Up to Date! In My PC... It's Showing That You've Merged My PR!?

**Comment by QAZIMAAZARSHAD** [comment]
Yes that was merged.

But create a new PR.

**Comment by skpandey885** [comment]
> Yes that was merged.
> 
> But create a new PR.

I am unable to create new PR its showing "There's Nothing to Compare"

**Comment by nlok5923** [comment]
> @nlok5923 have you merged any PR that caused this or have done any changes?
> 
> Resolve this if you find bug.

Sorry for late reply but @QAZIMAAZARSHAD those pr's which i approved and merged bought only functionality changes no of those dealt with UI changes.

**Pull request merged**
