### PR TITLE
Chores fixed in the registration form

### LINKED ISSUE #336: Chore fixes needed in registration form
## Describe the bug
Currently registration form is quite uncertain in it's field UI design.

some uncertainities: 
- text area should not be resizable (try `resize: none`).
- show password fields aren't aligned properly.
- Total registration component animation on hover 

## To Reproduce
1.  Head over to registration page

## Expected behavior
registration page should not have hover animation  and fix rest two bugs 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).
image

## Environment (please complete the following information):
 - OS: all
 - Browser: all

@QAZIMAAZARSHAD please take a look i don't think the animation on hover over registration and login page looks good i think we should keep it simple and sweet.

### PR DESCRIPTION
**Pull request by RiyaGupta89**

### CODE REVIEW

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD should we remove the hover animation from all the pages (login sign-up and forget password )

**Comment by QAZIMAAZARSHAD** [comment]
You opened this issue.
Check, the necessary changes have been made or not.


And yes, the login page, the sign-up page, and the forget-pass page should always be similar.

**Comment by nlok5923** [comment]
@RiyaGupta89 please remove the hover effect from all the pages and once please do provide a deployment link for testing purpose.

**Comment by RiyaGupta89** [comment]
@nlok5923 I have made the required changes. 
https://agitated-hypatia-4573ae.netlify.app/

**Review by nlok5923 — APPROVED** [review]
Thanks LGTM !!

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 make one more PR to remove the hover effect from the Feedback page.

**Pull request merged**
