### PR TITLE
Validation done

### PR DESCRIPTION
**Pull request by skpandey885**
#368 
Validation Fixed!
Hover Effect Removed!
Heading Added.
Minor Changes.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so we can review it.

**Comment by skpandey885** [comment]
https://skpandey885.github.io/Voters-Registration-Portal/

**Comment by QAZIMAAZARSHAD** [comment]
Not done.

image


Also, your repo is not updated.
Fetch upstream.

**Comment by QAZIMAAZARSHAD** [comment]
Completely update your repo.

Then clone.

Then push changes.

Validate every single field properly also generate sweet alert for wrong input.

**Comment by skpandey885** [comment]
Bhaiya i cloned the repo 2 hrs ago then added the changes and then pushed it! and Then create this new PR

**Comment by skpandey885** [comment]
And Yes There is A Validation Msg For every field! It shows a Msg!

**Comment by QAZIMAAZARSHAD** [comment]
image


See your branch is 7 commits behind.

Website has been updated, you have to fetch it again.

**Comment by skpandey885** [comment]
Oh Okey! so again i need to clone it?

**Comment by QAZIMAAZARSHAD** [comment]
> And Yes There is A Validation Msg For every field! It shows a Msg!

Nope.


If you have done something like this, but it is not reflecting in the link you shared.

**Comment by QAZIMAAZARSHAD** [comment]
> Oh Okey! so again i need to clone it?

Yes, clone the updated repo.
Then work.

**Comment by skpandey885** [comment]
Screenshot 2021-07-19 at 11 43 18 AM

**Comment by skpandey885** [comment]
It Might not show due to cache or slow internet! but I have added it!

**Comment by skpandey885** [comment]
Screenshot 2021-07-19 at 11 48 18 AM
Screenshot 2021-07-19 at 11 43 18 AM
Screenshot 2021-07-19 at 11 48 30 AM

**Comment by QAZIMAAZARSHAD** [comment]
Make a new PR with everything updated then we will see.

**Pull request closed without merging**
