### PR TITLE
Scrolltotop

### LINKED ISSUE #13: Add a scroll to top button
There should be scroll to top button
@QAZIMAAZARSHAD can i work on this issue under LGM=SOC'21 participant

### PR DESCRIPTION
**Pull request by kumarishalini6**
#### Issue Number
fixes #13 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD now you can proceed

**Comment by QAZIMAAZARSHAD** [comment]
Review your code once again.

Same lines repeated in CSS file.

Before making PR always review what lines of code you have changed.
Screenshot (109)

**Comment by kumarishalini6** [comment]
I have removed all the lines which appear 2 times
@QAZIMAAZARSHAD now you can proceed

**Comment by QAZIMAAZARSHAD** [comment]
You have not added scroll to top button in hindi_hime.html.

I'm saying this again.

First completely update your repo with main.
Them make the changes.
Then review everything, live demo as well as code.

Then only make PR.

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD I have added pre loader and scroll to top button both

**Comment by QAZIMAAZARSHAD** [comment]
To many unnecessary changes and deletions.

Try to make a new PR, only necessary additions and deletions.

First update your repo then proceed.

**Pull request closed without merging**
