### PR TITLE
Added the background image for the three files and fixed the issue.

### PR DESCRIPTION
**Pull request by Swarga-codes**
ISSUE #220 
fixes #

#### Describe the changes you've made
As I was assigned with the task of modifying the login portal , forgot password and the sign up portal but the background  image was not showing up so I noticed that due to some reasons or the other the background image was not pushed into the image directory I fetched upstream to bring the updated webpage and made the necesssary changes and again pushed the necessary files(including the image) this time.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
#### Additional context (OPTIONAL)
Screenshots of the three pages are as follows: 

Screenshot (188)

Screenshot (189)

Screenshot (191)

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by nlok5923** [comment]
@Swarga-codes thanks for pr please can you provide a test deployment link so that we can test changes.

**Comment by Swarga-codes** [comment]
> @Swarga-codes thanks for pr please can you provide a test deployment link so that we can test changes.

Sure! Check this link: https://swarga-codes.github.io/Voters-Registration-Portal/

**Comment by nlok5923** [comment]
@Swarga-codes please make UI symmteric you can observe in ss that footer of the login container has some extra padding also please do not add border radius. 
image

**Comment by nlok5923** [comment]
you add border radius in all the three pages i will suggest you to remove it

**Review by nlok5923 — CHANGES_REQUESTED** [review]
PTAL

**Comment by QAZIMAAZARSHAD** [comment]
Image not properly aligned on all pages.
image

Show password feature not working in login.html.

**Comment by Swarga-codes** [comment]
> Image not properly aligned on all pages.
> image
> 
> Show password feature not working in login.html.

I worked only with the CSS didn't make any changes to any function.

**Comment by QAZIMAAZARSHAD** [comment]
@Swarga-codes  see the difference.
Something must be wrong in your code.

https://qazimaazarshad.github.io/Voters-Registration-Portal/login.html
Screenshot (156)

https://swarga-codes.github.io/Voters-Registration-Portal/login.html
Screenshot (155)

**Comment by Swarga-codes** [comment]
> @Swarga-codes see the difference.
> Something must be wrong in your code.
> 
> https://qazimaazarshad.github.io/Voters-Registration-Portal/login.html
> Screenshot (156)
> 
> https://swarga-codes.github.io/Voters-Registration-Portal/login.html
> Screenshot (155)

You can check out I fixed that show password thing and as mentioned by @nlok5923 I removed the border radius from all the three forms and tried to adjust the background image as much as possible. Sir you can check it out @QAZIMAAZARSHAD .

**Comment by QAZIMAAZARSHAD** [comment]
Will review soon.

**Comment by QAZIMAAZARSHAD** [comment]
https://swarga-codes.github.io/Voters-Registration-Portal/login.html

https://swarga-codes.github.io/Voters-Registration-Portal/forgetPass.html

https://swarga-codes.github.io/Voters-Registration-Portal/sign-up.html

@Swarga-codes check these pages!!!

**Pull request closed without merging**
