### PR TITLE
designed login and signup page

### LINKED ISSUE #37: Create a login and sign-up page
I would like to work on this issue @QAZIMAAZARSHAD , Please assign me

### PR DESCRIPTION
**Pull request by coding-geek21**
#### Issue Number
fixes #37 

#### Describe the changes you've made
Created a Login and sign up page , Also made it responsive

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

https://user-images.githubusercontent.com/53329034/121525850-7373eb00-ca16-11eb-9d53-041eb2234124.mp4

### CODE REVIEW

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD Please review my PR and give your valuable feedback, Thank you :)

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by coding-geek21** [comment]
Sure sir

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD Resolved the conflicts please do check :)

**Comment by QAZIMAAZARSHAD** [comment]
@coding-geek21 how will a user reach the login and sign-up page?

You have forgotten to link the start button in index.html to redirect to login.html.

Do the changes.

**Comment by coding-geek21** [comment]
> @coding-geek21 how will a user reach the login and sign-up page?
> 
> You have forgotten to link the start button in index.html to redirect to login.html.
> 
> Do the changes.

Sorry ! Now only I noticed the changes made to home page , I will link it now

**Comment by coding-geek21** [comment]
> @coding-geek21 how will a user reach the login and sign-up page?
> 
> You have forgotten to link the start button in index.html to redirect to login.html.
> 
> Do the changes.

Done the changes.

**Comment by QAZIMAAZARSHAD** [comment]
This time you forgot to redirect the user to home.html after he/she logins or signs up.

Do the changes.

**Comment by QAZIMAAZARSHAD** [comment]
> This time you forgot to redirect the user to home.html after he/she logins or signs up.
> 
> Do the changes.

Resolve conflicts as well.

**Comment by coding-geek21** [comment]
> > This time you forgot to redirect the user to home.html after he/she logins or signs up.
> > 
> > Do the changes.
> 
> Resolve conflicts as well.

Sure

**Pull request closed without merging**
