### PR TITLE
Issue #328

### PR DESCRIPTION
**Pull request by stellashank**
Issue #328

### CODE REVIEW

**Comment by stellashank** [comment]
IMG_20210705_181055

**Comment by stellashank** [comment]
IMG_20210705_175123

**Comment by stellashank** [comment]
IMG20210705175112

**Comment by stellashank** [comment]
Screenshot_2021-07-05-19-21-54-33

**Comment by stellashank** [comment]
Screenshot_2021-07-05-19-23-08-40

**Comment by QAZIMAAZARSHAD** [comment]
image

Still no changes on the home page.

**Comment by QAZIMAAZARSHAD** [comment]
Looks like you have not pushed changes in style.css

**Comment by stellashank** [comment]
That help.html page is fine?!

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (20)


The header looks fine but you have added unnecessary horizontal width.

**Comment by stellashank** [comment]
Did the changes.
Do u confirm.

**Comment by QAZIMAAZARSHAD** [comment]
> Also redundant code.
> 
> <script> const chk = document.getElementById('chk'); chk.addEventListener('change', () => { document.body.classList.toggle('dark'); }); </script>

Same redundancy in home.html as well.

**Comment by QAZIMAAZARSHAD** [comment]
The header of the home page still the same.


Also, remove the horizontal width on the help page.

**Comment by stellashank** [comment]
Sir check now

**Comment by QAZIMAAZARSHAD** [comment]
@stellashank fine.

But it has raised one issue in flip logo.
image

**Comment by QAZIMAAZARSHAD** [comment]
https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/332

**Pull request merged**
