### PR TITLE
Feedback Form Added

### PR DESCRIPTION
**Pull request by skpandey885**
Issue No. #319

Features Added-
1. Feedback Form Created
2. Feedback Form Submit Page Created
3. Feedback Form Page Links Added To All The Pages
4. Responsiveness Improved

### CODE REVIEW

**Comment by nlok5923** [comment]
@skpandey885 why did you created a new pr ?

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 close the PR which you don't want to be evaluated.

Share screenshots or live demo link of the website.

**Comment by skpandey885** [comment]
1st Image- Feedback Form
2nd Image- Feedback Form Submitted Page
3rd Image- Feedback Form Link Added To All The Footers

Screenshot 2021-07-09 at 9 39 02 AM
Screenshot 2021-07-09 at 9 39 15 AM
Screenshot 2021-07-09 at 9 39 41 AM

**Comment by QAZIMAAZARSHAD** [comment]
On the submitted page replace 'Taken' with 'Received'.

And replace the next line with " We'll surely acknowledge your feedback and take necessary actions".

**Comment by nlok5923** [comment]
@skpandey885 also do ensure that text area should not be resizable. you can use `resize:none` property.

**Comment by skpandey885** [comment]
I don't Know Why I'm Facing Some Issues.
It Is Showing That Failed To Push When I'm Pushing My Changes After Commit!

**Comment by skpandey885** [comment]
I've Been Trying For an Hour But It's Not Working! Should I Delete This Pull Request And Create A Different One? It Might Work.

**Comment by nlok5923** [comment]
if that's the only solution left then go for it.

**Comment by skpandey885** [comment]
ok, I'm closing this one!

**Comment by skpandey885** [comment]
Hey! Its Still Not Working! What Should I do!  Please Check This Screenshot!


Screenshot 2021-07-10 at 4 35 39 PM

**Comment by QAZIMAAZARSHAD** [comment]
> Hey! Its Still Not Working! What Should I do! Please Check This Screenshot!
> 
> Screenshot 2021-07-10 at 4 35 39 PM

Search this error in StackOverflow you might get the solution.
Reach out to @nlok5923 if you can't resolve the issue.

**Comment by skpandey885** [comment]
> > Hey! Its Still Not Working! What Should I do! Please Check This Screenshot!
> > Screenshot 2021-07-10 at 4 35 39 PM
> 
> Search this error in StackOverflow you might get the solution.
> Reach out to @nlok5923 if you can't resolve the issue.

yeah i did but no solution worked! 
but still i am On it! and I will give you further updates!

**Comment by skpandey885** [comment]
Hey Im Still Not Able to Push Please Help Me!

**Comment by skpandey885** [comment]
@QAZIMAAZARSHAD  Bhaiya Can You still Merge The #342 Pull Request! Because It Contains All The Big Changes I Did!

**Comment by skpandey885** [comment]
> On the submitted page replace 'Taken' with 'Received'.
> 
> And replace the next line with " We'll surely acknowledge your feedback and take necessary actions".

I Will Change This Thing After You Accept This Pull request ..Then I would try pushing then it might work!

**Comment by QAZIMAAZARSHAD** [comment]
Fine, now make other PR to do required changes.

**Pull request merged**
