### PR TITLE
Improved UI of Landing page

### PR DESCRIPTION
**Pull request by dpshikha476**
Issue Fixed : #163

I have made some changes in the UI that includes the header, the start button, the toggle button for video and it is responsive.
Please review it and let me know you want some changes.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by dpshikha476** [comment]
Done!

**Comment by QAZIMAAZARSHAD** [comment]
Nice, but one problem. The header of index.html is large, missing flag, and different from others.

Look into this. Here is the website after your changes -> https://voters-registration-portal-1.qazimaazarshad.repl.co/

**Comment by dpshikha476** [comment]
> Nice, but one problem. The header of index.html is large, missing flag, and different from others.
> 
> Look into this. Here is the website after your changes -> https://voters-registration-portal-1.qazimaazarshad.repl.co/

Sir I have made the header's height small.  
I have given the tricolor background to the header and instead of the flag I have added the National emblem.

Should I replace the emblem with our flag? @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
No it's fine, but the headers of all pages must be the same.

Check responsiveness as well.

**Comment by dpshikha476** [comment]
I have updated the headers of all the pages and responsiveness is checked.

**Pull request merged**
