### PR TITLE
adjust zoom and language button

### PR DESCRIPTION
**Pull request by nitishapiplani**
adjusted zoom and language button

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Everythings perfectly fine @nitishapiplani but do the same changes in home_hindi.html that you did in home.html.

**Comment by nitishapiplani** [comment]
> Everythings perfectly fine @nitishapiplani but do the same changes in home_hindi.html that you did in home.html.

done

**Comment by QAZIMAAZARSHAD** [comment]
Always mention the issue number in PR description #77.

**Comment by nitishapiplani** [comment]
> Always mention the issue number in PR description #77.okkay

**Pull request merged**
