### PR TITLE
Update feedbackform.html

### PR DESCRIPTION
**Pull request by Junyi314**
I have done the validation for the feedback form(issue #368). Please check
I add the validation function for the button. And change the href link to inside the else in the validate function. The href is the reason that cannot validate the form.
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Junyi314 please share a live demo link of your website so I can review the changes.

**Comment by Junyi314** [comment]
> @Junyi314 please share a live demo link of your website so I can review the changes.

how do i share a live demo link

**Comment by Junyi314** [comment]
> @Junyi314 please share a live demo link of your website so I can review the changes.

https://junyi314.github.io/Voters-Registration-Portal/feedbackform.html

**Comment by QAZIMAAZARSHAD** [comment]
Great.

image

But the first name and last name accept numbers and special characters. This should be restricted.
If you wish you can work on this issue.

**Pull request merged**
