### PR TITLE
footer links addded

### LINKED ISSUE #271: Footer link should redirect to actual sites
## Describe the bug
- Currently the footer links under government of india section redirect to #

## To Reproduce
1. Head over to footer 
2. Click on any link under goverment of india section

## Expected behavior

- It should redirect to actual sites

## Logs
this links i am talking about
image

## Environment (please complete the following information):
 - OS: all
 - Browser: all

### PR DESCRIPTION
**Pull request by royalleads15**
#271 
fixes #271

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@royalleads15 there is one more page.

Form correction.html, apply changes in that also.

**Comment by QAZIMAAZARSHAD** [comment]
Forget pass also.

**Comment by royalleads15** [comment]
Sorry Sir due to some Issue it happen . Hope you didn't mind it

**Comment by QAZIMAAZARSHAD** [comment]
> Sorry Sir due to some Issue it happen . Hope you didn't mind it

What?

Everything's fine.

**Pull request merged**
