### PR TITLE
Improve the UI/UX of the home page content (not including header, foo…

### LINKED ISSUE #380: Improvement of UI/UX in the voter registration home page
## Is your feature request related to a problem? Please describe.
I think the UI/UX of the voter registration page can be improved

## Describe the solution you'd like
I would like to use some trending design idea of modern website design to make the interface looks clean and nice-looking

## Additional context
The adjustment of the font size is not neccessary since it does not do much changes, this can be solved by the responsive design to adjust the font size.

### PR DESCRIPTION
**Pull request by LeeSiangWei**
…ter)

#### Describe the changes you've made
1. Improve the overall UI of the home page content but not including header and footer (because header and footer will affect other pages)
2. Remove the font size increment and decrement since I had made the font size to be responsive when zoom in by using 'rem' instead of 'px'

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Belows are some of the screenshots

#### Test plan (OPTIONAL)
NA

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name her

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
The website has been updated.

I suggest go through the website again and update the header, footer accordingly.
Check responsiveness in mobile phone and other screens as well.

**Comment by QAZIMAAZARSHAD** [comment]
When you're done host your website and share the website link so I can review your changes.

**Comment by LeeSiangWei** [comment]
Means I need to change and design the header and footer you mean the header and footer had been modified by other contributors that I need to update in my repo?

**Comment by QAZIMAAZARSHAD** [comment]
> Means I need to change and design the header and footer you mean the header and footer had been modified by other contributors that I need to update in my repo?

Yes.

**Comment by QAZIMAAZARSHAD** [comment]
Also resolve conflicts.

**Comment by LeeSiangWei** [comment]
I had update the header and footer, but still the same design, so just to confirm that do I need to touch for the header and footer? or I update the content design first then header and footer later on? Because if modify once for all including the header and footer, I scare that I need to keep on updating due to others merged/updated.

**Comment by QAZIMAAZARSHAD** [comment]
First, resolve conflicts.

Then share a link to your website so I can review your PR.
Then I will suggest the changes that need to be done.

**Pull request closed without merging**
