### PR TITLE
Made footer responsive and other minor changes

### PR DESCRIPTION
**Pull request by RiyaGupta89**
#### Issue Number
fixes #219

#### Describe the changes you've made
I changed everything that ask me to correct and change. Made footer responsive as well.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [✔️] My code follows the code style of this project.
- [✔️] My change requires a change to the documentation.
- [✔️] I have updated the documentation accordingly.
- [✔️] I have added tests to cover my changes.
- [✔️] All new and existing tests passed.
- [✔️] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD  You have not raised the level of label?

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (140)

Still a problem in home.html.

**Comment by RiyaGupta89** [comment]
Oh sorry, I'll resolve it.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD You have not raised the level of label?

I will,

Create one more PR to resolve the issue.

Also, remove brackets from this email help[@]nationalvoterportal[.]gov[.]in.

**Comment by RiyaGupta89** [comment]
Okay, I'll resolve both the issues. Is it okay if I do it tomorrow?

**Comment by QAZIMAAZARSHAD** [comment]
> Okay, I'll resolve both the issues. Is it okay if I do it tomorrow?

Take your time.
No hurry

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD I've resolved the issues. Please check it.

**Pull request merged**
