### PR TITLE
Preloader

### LINKED ISSUE #34: Add a preloader
I want to add a attractive preloader

### PR DESCRIPTION
**Pull request by kumarishalini6**
#### Issue Number
fixes #34 

I have made a pre loader for the website

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD please have a look on this PR. Thanks

**Comment by QAZIMAAZARSHAD** [comment]
Will review soon.

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD Done

**Pull request merged**
