### PR TITLE
Validation Of The Form Added

### PR DESCRIPTION
**Pull request by skpandey885**
Issue #368 

Validation Feature  Of The Form Added.
Now Users will Have to enter All The Fields In Order To submit.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so we can review your changes.

**Comment by skpandey885** [comment]
How CAN I SHARE LINK? I mean I have not deployed the changes anywhere?

**Comment by skpandey885** [comment]
Here Are Some Screenshots!

Screenshot 2021-07-16 at 10 18 14 PM
Screenshot 2021-07-16 at 10 18 31 PM

**Comment by QAZIMAAZARSHAD** [comment]
> How CAN I SHARE LINK? I mean I have not deployed the changes anywhere?

Host your website then share.

**Comment by skpandey885** [comment]
> > How CAN I SHARE LINK? I mean I have not deployed the changes anywhere?
> 
> Host your website then share.

Bhaiya Check The Screenshots for changes!

**Comment by nlok5923** [comment]
@skpandey885 just deploy your forked repo to gh pages or netlify so that we can test the changes.

**Comment by skpandey885** [comment]
ok

**Comment by skpandey885** [comment]
https://skpandey885.github.io/Voters-Registration-Portal/

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 check again.

image

Even this is getting accepted.
Validate every field properly.

**Comment by skpandey885** [comment]
> @skpandey885 check again.
> 
> image
> 
> Even this is getting accepted.
> Validate every field properly.

Done Bhaiya!

**Comment by QAZIMAAZARSHAD** [comment]
Not done.

image


Validate every single field.
Also, change the blue background to light pink as in the scroll bar.

And most important your repo is not updated, fetch upstream completely update then push changes.

**Comment by skpandey885** [comment]
> Not done.
> 
> image
> 
> Validate every single field.
> Also, change the blue background to light pink as in the scroll bar.
> 
> And most important your repo is not updated, fetch upstream completely update then push changes.

Bhaiya I Have Validated Every Field ... and Changed The Background Colour! The Changes Are taking time(to get updated) because of the cache Of browsers. Try Opening the website using incognito mode once. You'll be able to see the changes.

**Comment by skpandey885** [comment]
Screenshot 2021-07-17 at 12 20 39 PM
Screenshot 2021-07-17 at 12 21 16 PM
Screenshot 2021-07-17 at 12 21 35 PM

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 I think you are not understanding.

First name last name these fields should accept only alphabets but they are accepting all characters.
Similarly, email is getting accepted without @gmail.com
Zip code should accept only numbers but it is accepting all the characters.

Look into this.

Also first update your repo. Fetch upstream then proceed further.

And remove the pink hover effect, keep it simple. Either keep the background color like present or change it to pink but no hover effect.

**Comment by skpandey885** [comment]
> @skpandey885 I think you are not understanding.
> 
> First name last name these fields should accept only alphabets but they are accepting all characters.
> Similarly, email is getting accepted without @gmail.com
> Zip code should accept only numbers but it is accepting all the characters.
> 
> Look into this.
> 
> Also first update your repo. Fetch upstream then proceed further.
> 
> And remove the pink hover effect, keep it simple. Either keep the background color like present or change it to pink but no hover effect.

Oh okey now I got it!

**Comment by nlok5923** [comment]
@skpandey885 please do remove the hover effect too.

**Comment by skpandey885** [comment]
All Things Done Bhaiya!

**Comment by skpandey885** [comment]
I was Facing some issues while I was fetching the upstream master.

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 your branch is 25 commits behind my branch.
Fetch upstream. Then push changes.

zip code and mobile number fields have already been validated.
Check -> https://qazimaazarshad.github.io/Voters-Registration-Portal/

**Comment by skpandey885** [comment]
so I have to close this pr?

**Comment by skpandey885** [comment]
> @skpandey885 your branch is 25 commits behind my branch.
> Fetch upstream. Then push changes.
> 
> zip code and mobile number fields have already been validated.
> Check -> https://qazimaazarshad.github.io/Voters-Registration-Portal/

I checked bhaiya but there are no changes in it! I mean it's the previous one only!

**Comment by QAZIMAAZARSHAD** [comment]
> > @skpandey885 your branch is 25 commits behind my branch.
> > Fetch upstream. Then push changes.
> > zip code and mobile number fields have already been validated.
> > Check -> https://qazimaazarshad.github.io/Voters-Registration-Portal/
> 
> I checked bhaiya but there are no changes in it! I mean it's the previous one only!

Nope,  


footer and header have also been updated, few more changes.


Always keep your repo updated when working on any issue.

**Comment by skpandey885** [comment]
Ok Bhaiya! Thanks For The constant Guidance

**Pull request closed without merging**
