### PR TITLE
Scrolltotop

### LINKED ISSUE #13: Add a scroll to top button
There should be scroll to top button
@QAZIMAAZARSHAD can i work on this issue under LGM=SOC'21 participant

### PR DESCRIPTION
**Pull request by kumarishalini6**
#### Issue Number
fixes #13 

I have added scroll to top button in every page and also add pre loader at home page.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Reveiw your code once again.

You have same lines in CSS twice for scrolltotop.

**Comment by kumarishalini6** [comment]
> Reveiw your code once again.
> 
> You have same lines in CSS twice for scrolltotop.

sorry about that, 
now you can proceed

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by kumarishalini6** [comment]
Hey I guess you have close the issue by mistake

**Comment by QAZIMAAZARSHAD** [comment]
> Hey I guess you have close the issue by mistake

I have not closed the issue.
I have closed the pull request because it had conflicts.

**Pull request closed without merging**
