### PR TITLE
Added Translation

### PR DESCRIPTION
**Pull request by SanjeevKumar22**
#### Issue Number
fixes #

ISSUE #59
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
Added The translation feature to the page

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by SanjeevKumar22** [comment]
Capture1
Capture

**Comment by QAZIMAAZARSHAD** [comment]
The site has been updated a lot. Have a look -> https://qazimaazarshad.github.io/Voters-Registration-Portal/
Review your changes.

Update your repo first then do the changes.

And after verifying everything live demo, responsiveness, and code then only make PR.

**Comment by SanjeevKumar22** [comment]
> The site has been updated a lot. Have a look -> https://qazimaazarshad.github.io/Voters-Registration-Portal/
> Review your changes.
> 
> Update your repo first then do the changes.
> 
> And after verifying everything live demo, responsiveness, and code then only make PR.

translate to all language?issue assign to me

**Comment by QAZIMAAZARSHAD** [comment]
> > The site has been updated a lot. Have a look -> https://qazimaazarshad.github.io/Voters-Registration-Portal/
> > Review your changes.
> > Update your repo first then do the changes.
> > And after verifying everything live demo, responsiveness, and code then only make PR.
> 
> translate to all language?issue assign to me

Yes you are assigned you can see.

**Pull request closed without merging**
