### PR TITLE
Improvement of UI/UX in hompage content v3

### LINKED ISSUE #380: Improvement of UI/UX in the voter registration home page
## Is your feature request related to a problem? Please describe.
I think the UI/UX of the voter registration page can be improved

## Describe the solution you'd like
I would like to use some trending design idea of modern website design to make the interface looks clean and nice-looking

## Additional context
The adjustment of the font size is not neccessary since it does not do much changes, this can be solved by the responsive design to adjust the font size.

### PR DESCRIPTION
**Pull request by LeeSiangWei**
#### Describe the changes you've made
Improve the UI/UX of the hom page content not including the header and footer

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
this is the link (kindly navigate to homepage to view the changes):
https://leesiangwei.github.io/Voters-Registration-Portal/

screenshots of new changes made:

#### Test plan (OPTIONAL)
NA

#### Checklist
- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by LeeSiangWei** [comment]
Hi, I had made the changes for those you had mentioned before, kindly have a check, thank you.

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

**Comment by QAZIMAAZARSHAD** [comment]
@LeeSiangWei would you like to improve the UI of the form-correction page as well.
https://qazimaazarshad.github.io/Voters-Registration-Portal/form-correction.html

**Comment by LeeSiangWei** [comment]
Hmmm I think I will raise the issue and modify if I am free upcoming weeks, because these weeks quite busy in assignments. Thank you ya

**Pull request merged**
