### PR TITLE
Added a Modal pop-up to display List of Supported Documents

### LINKED ISSUE #6: Display list of supported documents
A pop-up containing the list of supporting documents should appear on clicking "List of supported documents" link.

image

Pop-up could be an image or text.

### PR DESCRIPTION
**Pull request by Sourav61**
#### Issue Number
fixes #6

#### Describe the changes you've made
Made a modal pop-up which opens when clicked on "List of supported documents"

1. In Home.html, i added the "myBtn" named id to "List of supported documents", added ordered list for all main headings 
and unordered list for subpoints.
2. In Style.css, i did styling for modal, modal-content, close , close:hover, close:focus, ::after, ::before, head, ol ,ul
classes, img tag and myBtn id.
3.Added index.js for proper functioning of modal pop-up.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### CODE REVIEW

**Comment by Sourav61** [comment]
@QAZIMAAZARSHAD Sir pls review and check for any issues!!

**Comment by QAZIMAAZARSHAD** [comment]
No improvement, same as before.

Your CSS changes are disturbing index.html.
You forgot to link, index.js in home.html.
Your popup design is also bad, the popup occupies the entire screen, and the scroll bar is active, making the feature look like a bug.

**Comment by QAZIMAAZARSHAD** [comment]
@Sourav61 you can take the help of @nlok5923 to resolve this issue.

**Comment by Sourav61** [comment]
https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/pull/277#issuecomment-869390077

Which things are being disturbed in index.html as for me it is working fine for me?

Capture9

**Comment by Sourav61** [comment]
@QAZIMAAZARSHAD Sir i have linked index.js in Home.html as you can see in screenshot below!!

Capture10

**Comment by QAZIMAAZARSHAD** [comment]
> [#277 (comment)](https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/pull/277#issuecomment-869390077)
> 
> Which things are being disturbed in index.html as it is working fine for me @QAZIMAAZARSHAD Sir?
> 
> Capture9

image

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Sir i have linked index.js in Home.html as you can see in screenshot below!!
> 
> Capture10

Oo, my mistake.

But still pop-up is not up to the mark, try to improve.

**Comment by Sourav61** [comment]
Sir instead of modal popup can i make an alert in a new page @QAZIMAAZARSHAD Sir??

**Comment by Sourav61** [comment]
https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/pull/277#issuecomment-869399290

This issue is resolved, Only styling is left @QAZIMAAZARSHAD sir!!

**Comment by QAZIMAAZARSHAD** [comment]
Okk but resolve the css issue.

And share a live demo link.

**Pull request closed without merging**
