### PR TITLE
print functionality added

### LINKED ISSUE #226: Improve print form functionality
Print function prints the entire web page including header, footer, captcha, etc.

It should work properly and only the submitted form should be printed.

### PR DESCRIPTION
**Pull request by royalleads15**
#226 
fixes #226 

#### Describe the changes you've made
Functionality of print button added

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

#### Additional context (OPTIONAL)
print

#### Test plan (OPTIONAL)
Fill the data and click on print button

#### Checklist

&#9745;  My code follows the code style of this project.
&#9745;  I have added tests to cover my changes.
&#9745;  All new and existing tests passed.
&#9745;  The title of my pull request is a short description of the requested changes.
&#9745; Open Source Program names : LGMSOC

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Improved...

But still many things like choose state, radio buttons are not working.

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD sir as this issue is merged, so will i get points for that Or not  ?

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (166)

This means your PR will be awarded points.

**Comment by QAZIMAAZARSHAD** [comment]
But the issue is still unresolved that's why I decreased the level.

I have opened another issue, you can start working if you want to fix bug.

**Pull request merged**
