### PR TITLE
Updated Footer Copyright Year

### PR DESCRIPTION
**Pull request by Shaishav0507**
#### Issue Number #41
fixes  

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Additional context (OPTIONAL)
Thanks for giving me this opportunity to work on this project.

Issue number #41 

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Shaishav0507 this is not how you create a PR.

Always mention the issue number in the PR description.

**Comment by Shaishav0507** [comment]
I have done it.
Thanks for letting me know.

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by Shaishav0507** [comment]
What conflicts are there ?

**Comment by QAZIMAAZARSHAD** [comment]
Conflict it index.html.
It is due to recent updates.

Create a new branch and fetch upstream from the main. Then do only the necessary changes then make PR.

If still stuck, reach mentors in the slack channel.

**Comment by Shaishav0507** [comment]
Should I make another PR ?

**Comment by Shaishav0507** [comment]
I have already made another PR #80 please check it

**Pull request closed without merging**
