### PR TITLE
Aligned help page in desktop view

### PR DESCRIPTION
**Pull request by mayank-wadhwa-git**
#### Describe the changes you've made
Aligned Help page in desktop view

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Mention issue number like this #372.

**Comment by QAZIMAAZARSHAD** [comment]
@mayank-wadhwa-git nothing changed.

image

**Comment by mayank-wadhwa-git** [comment]
> @mayank-wadhwa-git nothing changed.
> 
> image

It's Changed

**Comment by QAZIMAAZARSHAD** [comment]
What have you changed?

**Comment by mayank-wadhwa-git** [comment]
Help Desk and 3 more pages - Personal - Microsoft​ Edge 26-07-2021 12_28_31

Check

**Comment by mayank-wadhwa-git** [comment]
> What have you changed?

I changed css of help page

**Comment by QAZIMAAZARSHAD** [comment]
Yes, GitHub page took long time to update.

**Comment by mayank-wadhwa-git** [comment]
> Yes, GitHub page took long time to update.

Now is it fine?

**Comment by QAZIMAAZARSHAD** [comment]
Yes.

Fill the form.

**Comment by mayank-wadhwa-git** [comment]
> Yes.
> 
> Fill the form.

okk

**Pull request merged**
