### PR TITLE
#292

### LINKED ISSUE #292: Beautify Code
## Problem
I find it difficult to navigate through the code because many elements aren't indented properly. Most of the work can't be done without using Ctrl + F :(

## Proposed Solution
I'd like to add proper indentation and new lines to all the files to enhance the readability.

## Proposed tags
LGMSOC-2021

### PR DESCRIPTION
**Pull request by Albert-Jokelin**
Took me a while but I think I've resolved #292

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

Check carefully all your changes must be updated.

**Comment by QAZIMAAZARSHAD** [comment]
Add all the CSS files in the CSS folder.

All the js files in the js folder.

All the HTML file in HTML folder except index.html.

**Comment by nlok5923** [comment]
@Albert-Jokelin please provide proper description and appropriate pr title. the current title is not at all correct.

**Comment by QAZIMAAZARSHAD** [comment]
@Albert-Jokelin I am closing this PR.

Make a new one when you are done with everything.

**Pull request closed without merging**
