### PR TITLE
Feedback form

### PR DESCRIPTION
**Pull request by skpandey885**
Issue No. #319 

1.Feedback Form Created
2. Design Improved
3. Responsiveness Improved

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 this website will be used by Indian citizens only so remove country.

Remove this -> "Any Feature Missing? If Yes! Please Mention It". I think there should be only one input box.

Add a few more radio button questions.


Link this page with the footer of all pages.

**Comment by QAZIMAAZARSHAD** [comment]
Add pop-up alert for validation.

Also, your feedback submitted message on form submission.

**Comment by skpandey885** [comment]
OK Bhaiya

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD where we will be saving the feedback responses ?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD where we will be saving the feedback responses?

@nlok5923 this is just a demo website, currently no backend on this website.

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD do we have any futures plan to take this demo website and intergrate server and database with it ?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD do we have any futures plan to take this demo website and integrate the server and database with it?

Yes

**Pull request closed without merging**
