### PR TITLE
FinalValidate

### PR DESCRIPTION
**Pull request by skpandey885**
#368 
Validation Added

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Do share a link for reviewing every time you make PR.

**Comment by skpandey885** [comment]
https://skpandey885.github.io/Voters-Registration-Portal/

**Comment by QAZIMAAZARSHAD** [comment]
Again.


image

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 please understand that your repo is not updated. Check your header and footer.

I can't accept your changes if it is not updated.

Also again all fields are not validated, only the email field is fine.
And no prompt, no error message is appearing when entering wrong input.
And you have only removed the hover color only, the other hover effect is still present.

**Comment by skpandey885** [comment]
Bhaiya Its fine! I mean Its shows a msg when the field is in the frame of the screen otherwise it shows a blue box around the fields. So It Think Its Fine Bhaiya!

**Comment by skpandey885** [comment]
> @skpandey885 please understand that your repo is not updated. Check your header and footer.
> 
> I can't accept your changes if it is not updated.
> 
> Also again all fields are not validated, only the email field is fine.
> And no prompt, no error message is appearing when entering wrong input.
> And you have only removed the hover color only, the other hover effect is still present.

I Have Fetched Multiple Time Since Morning. still can't Figue out why Its Not Working

**Comment by QAZIMAAZARSHAD** [comment]
> Bhaiya Its fine! I mean Its shows a msg when the field is in the frame of the screen otherwise it shows a blue box around the fields. So It Think Its Fine Bhaiya!

I don't meant that.

In screenshot see, in name numbers are getting accepted, zip code number of digits must be 6, state city cannot accept a number.

**Comment by QAZIMAAZARSHAD** [comment]
@nlok assist @skpandey885.

**Comment by skpandey885** [comment]
1. Zip Code Will Only Accept up to 6 numbers.
2. No Hover Effect
3. First Name, Last Name, City, State Will Only Accept Alphabetical Texts.
4. There will Be Blue Border Alert If Any Field Is Left
5. If The field Is In The Frame Of The Screen Then it will pop a message(browser in built aleart)

Any More Changes? Please Mention! I will Fix-It and push it!

**Comment by QAZIMAAZARSHAD** [comment]
Didn't get 5th point.

Zipcode should accept exactly 6 numbers (not up to)

Instead of a blue border alert, as soon as the user enters a wrong input, or forgets any input it should display a sweet alert that this is not the format.
Like the alert on the login page.

**Comment by skpandey885** [comment]
> Didn't get 5th point.
> 
> Zipcode should accept exactly 6 numbers (not up to)
> 
> Instead of a blue border alert, as soon as the user enters a wrong input, or forgets any input it should display a sweet alert that this is not the format.
> Like the alert on the login page.

Ok I Got it!

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 any new updates?

Make new PR when you are done.

**Pull request closed without merging**
