### PR TITLE
Bottom text at login page made clickable.

### PR DESCRIPTION
**Pull request by asdsyd**
#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
added <a> tags to make the words at the bottom of login page clickable.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
none 

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Review by nlok5923 — CHANGES_REQUESTED** [review]
Please revert all the unnecessary changes

**Comment by asdsyd** [comment]
> Please revert all the unnecessary changes 

What unnecessary changes? How do I remove them ? I added new tags for clickable links. It added space thru out the code how do I get rid of that? Thanks

**Comment by QAZIMAAZARSHAD** [comment]
@asdsyd always mention issue number like this #339.

**Comment by QAZIMAAZARSHAD** [comment]
@asdsyd see in the top right corner there are 329 additions and 300 deletions since you were working only on the footer links so there should be hardly only 15-20 line changes but you have changed so many things.

Fetch upstream again and do only the necessary changes.

**Comment by QAZIMAAZARSHAD** [comment]
@nlok5923 since this project is also part of DCP so before adding labels ask participants which program they belong to.

**Pull request closed without merging**
