### PR TITLE
Fixed unresponsiveness

### PR DESCRIPTION
**Pull request by Albert-Jokelin**
Hey!

I've fixed the unresponsiveness. Pls Check out.

SS:
Voter Login - Opera 6_21_2021 11_28_18 PM

### CODE REVIEW

**Comment by nlok5923** [comment]
canyou please provide a static deployment at netlify/gh-pages so that we can test the changes.

**Comment by QAZIMAAZARSHAD** [comment]
@Albert-Jokelin you have disturbed the desktop view.
image


Also, a little bit padding is needed here 
image

**Comment by QAZIMAAZARSHAD** [comment]
And you have to improve the responsiveness of every single page.

Forgetpass.html, signup page, login page, help page.

**Comment by QAZIMAAZARSHAD** [comment]
And always mention the issue number in PR description like this #227.

**Comment by Albert-Jokelin** [comment]
Sure, I'll do it and get back to you in a while

**Comment by harishpansari** [comment]
I can work on this. assign to me.

**Pull request closed without merging**
