### PR TITLE
In mobile view the opening video does not occupies entire screen #298

### PR DESCRIPTION
**Pull request by Cartikx3**
Issue Number - #298 
 
#### Describe the changes you've made
i have added a media file for the mobile view that fits the video when the user open the portal in mobile .

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names LGM-SOC'21

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Share the website link so I can review your changes.

**Comment by Cartikx3** [comment]
Cartikx3.github.io

**Comment by Cartikx3** [comment]
https://cartikx3.github.io/

**Comment by QAZIMAAZARSHAD** [comment]
image


No done check desktop view as well

**Comment by QAZIMAAZARSHAD** [comment]
image


The mobile view is also not perfect.

**Comment by Cartikx3** [comment]
The issue is that with the desktop view is -

the resolution of the last image in the video is less compared to others so if i stretches the last image in the video to make it look balanced it will make the whole video stretched and the video becomes blurry.

in that video each and every image is of same size but the last image is of different size .

The problem is with video itself.

I cant fix it without making the video blurry or removing that part from the video .

**Comment by Cartikx3** [comment]
Please check again for mobile view  https://cartikx3.github.io/

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD merging this pr as the changes done are fine.

**Review by nlok5923 — APPROVED** [review]
LGTM

**Pull request merged**
