### PR TITLE
Beginning Text Font Changed

### PR DESCRIPTION
**Pull request by skpandey885**
Issue No. #361

Changes Made 👍
Beginning Text Font Changed.

### CODE REVIEW

**Comment by nlok5923** [comment]
@skpandey885 did @QAZIMAAZARSHAD suggested you using lato family.

**Comment by skpandey885** [comment]
> @skpandey885 did @QAZIMAAZARSHAD suggested you using lato family.

No, I Showed Him That Font In Issue #361  and It Looked Nice So I implemented It.

**Comment by nlok5923** [comment]
> > @skpandey885 did @QAZIMAAZARSHAD suggested you using lato family.
> 
> No, I Showed Him That Font In Issue #361 and It Looked Nice So I implemented It.

Ok @skpandey885 @QAZIMAAZARSHAD please confirm if lato looks fine

**Comment by QAZIMAAZARSHAD** [comment]
> @skpandey885 did @QAZIMAAZARSHAD suggested you using lato family.

@skpandey885 wanted to do this change so I allowed it.


@nlok5923 if you don't think it's fine, then close this issue and PR.

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD i think this changes are fine

**Pull request merged**
