### PR TITLE
Added the login and signup page

### LINKED ISSUE #37: Create a login and sign-up page
I would like to work on this issue @QAZIMAAZARSHAD , Please assign me

### PR DESCRIPTION
**Pull request by khushi-purwar**
#### Issue Number
fixes #37

#### Describe the changes you've made

I have added two files signup.html and login.html. Please reveiw it.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by khushi-purwar** [comment]
@QAZIMAAZARSHAD Please have a look on this PR

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by khushi-purwar** [comment]
> Resolve conflicts

Okay sir

**Comment by QAZIMAAZARSHAD** [comment]
Try to create new PR.
First fetch upstream. It will resolve the conflicts.

**Pull request closed without merging**
