### PR TITLE
Now social media links are opening in another tab.

### LINKED ISSUE #267: Social media links of the footer should be open in another tab
The links opening in the same tab want to open it into another tab.
Please assign me this issue.

### PR DESCRIPTION
**Pull request by tjanhvi**
#### Issue Number
fixes #267

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

image

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi apply it in all pages.

**Comment by tjanhvi** [comment]
okay :)

**Comment by tjanhvi** [comment]
> @tjanhvi apply it in all pages.

That means in every pages whether it is register page, help desk page.................. in all pages ?

**Comment by QAZIMAAZARSHAD** [comment]
Apply the same changes to all pages.

**Pull request closed without merging**
