### PR TITLE
Improve the UI/UX of the home page content (not including header, foo…

### LINKED ISSUE #380: Improvement of UI/UX in the voter registration home page
## Is your feature request related to a problem? Please describe.
I think the UI/UX of the voter registration page can be improved

## Describe the solution you'd like
I would like to use some trending design idea of modern website design to make the interface looks clean and nice-looking

## Additional context
The adjustment of the font size is not neccessary since it does not do much changes, this can be solved by the responsive design to adjust the font size.

### PR DESCRIPTION
**Pull request by LeeSiangWei**
…ter)

#### Describe the changes you've made
Improve the UI/UX of the hom page content not including the header and footer

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
this is the link (kindly navigate to homepage to view the changes):
https://leesiangwei.github.io/Voters-Registration-Portal/

these are some sample screenshots:

#### Test plan (OPTIONAL)
NA

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Delete the PR which you don't want to be merged.

**Comment by LeeSiangWei** [comment]
I had closed the request, have a check whether I done correctly? Thanks

**Comment by QAZIMAAZARSHAD** [comment]
@LeeSiangWei nice work. It looks great.

But few things can still be improved.

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (78)
The position of "Note fields" line does not looks good shift it left a bit just above the form margin.

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (79)

Remove these dashes "--" from every drop-down list.
Shift the "select" list upwards just a bit so it is aligned with the line.

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (80)
 
Delete the Age input, shift year, month in line.
Remove the gap between date.
Add 12 and remove 0 in the month list.

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (81)

Correct this also.

**Comment by QAZIMAAZARSHAD** [comment]
**And most important!!** There is very little contrast between light green background and white input fields.

Change these color combinations.

Choose the colour of your choice it must look good.

**Comment by LeeSiangWei** [comment]
Ok, I will proceed to the changes. Thanks

**Pull request closed without merging**
