### PR TITLE
adding homepage

### LINKED ISSUE #20: Design a Home page
@QAZIMAAZARSHAD  i think there should be a styled, attractive home page  , there should be a button after clicking on that button voters can enter on the main that.

@QAZIMAAZARSHAD can i work on this issue under LGM-SOC'21

### PR DESCRIPTION
**Pull request by kumarishalini6**
#### Issue Number
fixes #20 

#### Describe the changes you've made
I have design a home page .

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD  please have a look on this PR , i you need some change please let me know and it is responsive too.

**Comment by kumarishalini6** [comment]
And if you need i can send a short video recording too.

**Comment by QAZIMAAZARSHAD** [comment]
Great job @kumarishalini6.

What is the purpose of this button?
image

**Comment by kumarishalini6** [comment]
For play and pause

**Comment by QAZIMAAZARSHAD** [comment]
> For play and pause the video

This button is not working I guess.

**Comment by kumarishalini6** [comment]
please check it once again because it is working , if you want i can send you the video

**Comment by QAZIMAAZARSHAD** [comment]
> please check it once again because it is working, if you want I can send you the video

Got it, my mistake.

**Comment by kumarishalini6** [comment]
> Great job @kumarishalini6.
> 
> What is the purpose of this button?
> image

@QAZIMAAZARSHAD can I ask you something??
How you guys are able to check the changes (UI) in the desktop

**Comment by QAZIMAAZARSHAD** [comment]
Just copy-paste your changes in another copy of the project.

**Comment by kumarishalini6** [comment]
> Just copy-paste your changes in another copy of the project.

Ok just curious to know

**Comment by QAZIMAAZARSHAD** [comment]
@kumarishalini6 resolve conflicts.

**Comment by kumarishalini6** [comment]
@kumarishalini6  Done

**Pull request merged**
