### PR TITLE
Fixed Logo

### LINKED ISSUE #332: Correct the flip logo feature and also increase logo size
image

### PR DESCRIPTION
**Pull request by Garima-7**
#### Describe the changes you've made
https://garima-7.github.io/Voters-Registration-Portal/

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Garima-7 you are part of LGMSoC, DCP or both?

**Comment by Garima-7** [comment]
LGMSOC

**Comment by QAZIMAAZARSHAD** [comment]
@Garima-7 check the help and feedback page.

Also, the logo in the footer has been modified only on the login page do it on every page.
And you have also shifted the logo in the footer, don't change the position.

**Comment by Garima-7** [comment]
> @Garima-7 check the help and feedback page.
> 
> Also, the logo in the footer has been modified only on the login page do it on every page.
> And you have also shifted the logo in the footer, don't change the position.

ohk will correct it

**Pull request closed without merging**
