### PR TITLE
Feedback Form Submission page improved

### LINKED ISSUE #391: Improving UI Design of feedback-form-submission page
## Is your feature request related to a problem? Please describe.
The page doesn't look attractive and doesn't comply to the UI/UX design

## Describe the solution you'd like
Making the text more distributed and nicely presented

image

### PR DESCRIPTION
**Pull request by gunjan-g**
#### Describe the changes you've made
Aligned the text in accordance to UI design

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Screenshot of applied changes
image

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] LGMSOC'21

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Check responsiveness as well.

And share a deployment link to your website so I can also review your changes.

**Comment by gunjan-g** [comment]
> Check responsiveness as well.
> 
> And share a deployment link to your website so I can also review your changes.

ok

**Comment by gunjan-g** [comment]
@QAZIMAAZARSHAD here is the link:
https://gunjan-g.github.io/Voters-Registration-Portal/

**Comment by gunjan-g** [comment]
@QAZIMAAZARSHAD here is the link:
https://gunjan-g.github.io/Voters-Registration-Portal/feedbackformsubmitted.html

**Comment by QAZIMAAZARSHAD** [comment]
image

Check responsiveness.

Also, remove the hover effect.

**Comment by gunjan-g** [comment]
> image
> 
> Check responsiveness.
> 
> Also, remove the hover effect.

removing the hover effect from both desktop as well as mobile view?

**Comment by gunjan-g** [comment]
@QAZIMAAZARSHAD I've to remove the hover effect from both the laptop and mobile view or just from the mobile view

**Pull request closed without merging**
