### PR TITLE
Changed footer size in mobile

### PR DESCRIPTION
**Pull request by nik464**
#### Fixes #(issue number)
#404 
 

#### Describe the changes you've made
I have  changed size of the footer in mobile. As screen reduces size from 992 px, footer height becomes 40 px instead of 80 px.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
No there is no unusual behaviour

#### Deploy your changes to github page or netlify and mention deployment link:
Add the deployment link here.

#### Test plan (OPTIONAL)
You can check index. html and change the size of the page by inspect element.

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Host your website and share the website link so I can review your changes.

**Comment by nik464** [comment]
https://hardcore-bell-2341cc.netlify.app/    

For less then 992, that is small screen footer becomes half.

**Comment by QAZIMAAZARSHAD** [comment]
Fetch upstream your repo is 26 commits behind.

**Comment by QAZIMAAZARSHAD** [comment]
And nothing has changed.
It is similar.

Check
image

**Comment by QAZIMAAZARSHAD** [comment]
Size of footer is same.

**Comment by QAZIMAAZARSHAD** [comment]
After the changes check every single page.

Then only make PR.

**Comment by nik464** [comment]
ok is it not working for index?

**Comment by QAZIMAAZARSHAD** [comment]
No need to change the footer of the index page. That's perfectly fine.

The problem is with other pages.

**Pull request closed without merging**
