### PR TITLE
Signup and login page

### PR DESCRIPTION
**Pull request by urvashiparashar**
Issue #37 
I have created a login and signup page using html,css and javascript . The components of css allows to have animation effect on the designed webpage. Html allows to create a webpage syntactically as per user and js allows it to dynamically deploy.

Please review it.

### CODE REVIEW

**Comment by urvashiparashar** [comment]
Added download button

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by urvashiparashar** [comment]
> Resolve conflicts

Is this okay now?

**Comment by QAZIMAAZARSHAD** [comment]
no

**Comment by QAZIMAAZARSHAD** [comment]
Try to create a new PR.
First, fetch upstream then make the changes.

**Pull request closed without merging**
