### PR TITLE
clickable footer links

### PR DESCRIPTION
**Pull request by asdsyd**
#### Issue Number
 #348 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
ADDED <A> TAGS 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) LGMSOC21

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@asdsyd resolve conflicts.

Fetch upstream.

Now there is a feedback page linked to the feedback link.
Also, do these changes in the footer of all pages.

**Comment by asdsyd** [comment]
done

**Comment by QAZIMAAZARSHAD** [comment]
Again you forgot to do the changes in other pages.

**Comment by QAZIMAAZARSHAD** [comment]
Do it in every single page.
Forget pass,
FAQ.
signup,
formcorrection,
Home
feedback

**Comment by asdsyd** [comment]
oh okay

**Comment by asdsyd** [comment]
hey please look into it. Done #339

**Comment by QAZIMAAZARSHAD** [comment]
You forgot the feedback and feedbacksubmitted page.

**Comment by asdsyd** [comment]
done sorry my bad 😅

**Comment by QAZIMAAZARSHAD** [comment]
> hey please look into it. Done #339

@asdsyd you have to mention this issue number in PR description in PR description instead of PR number.

**Comment by asdsyd** [comment]
Ok thank you for helping me out. 👍I am a beginner.

**Comment by QAZIMAAZARSHAD** [comment]
> Ok thank you for helping me out. 👍I am a beginner.

@asdsyd you did solve the issue but it was not perfect.
In few pages, it is appearing like a blue underline.
In few pages, a blue underline is appearing on hover.

I suggest you to open a new issue to make footer links uniform.
Without hover it should be similar like it was before.
On hover text color should change to blue color, no underline.

**Pull request merged**
