### PR TITLE
added correction form

### LINKED ISSUE #21: Create a similar form for correction of voter details
I would like to work on this issue please assign me @QAZIMAAZARSHAD

### PR DESCRIPTION
**Pull request by coding-geek21**
#### Issue Number
fixes #21 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD Please review my PR

**Comment by QAZIMAAZARSHAD** [comment]
Nice @coding-geek21 but how will the user access this form?

You have not linked this page anywhere.

**Comment by coding-geek21** [comment]
> Nice @coding-geek21 but how will the user access this form?
> 
> You have not linked this page anywhere.

Can i do it in separate issue? like creating a dashboard where user can find new-enrollment form(home.html) and this correction form

**Comment by QAZIMAAZARSHAD** [comment]
> > Nice @coding-geek21 but how will the user access this form?
> > You have not linked this page anywhere.
> 
> Can i do it in separate issue? like creating a dashboard where user can find new-enrollment form(home.html) and this correction form. when user logins, they can see dashboard

Okk fine.

Open issue.

**Comment by royalleads15** [comment]
corr1
corr2
corr3
@QAZIMAAZARSHAD  Sir have a look on this if this looks fine then I can make PR.

**Comment by QAZIMAAZARSHAD** [comment]
@royalleads15 it is fine but this issue has already been resolved and the merged PR is perfectly fine.

You can leave this issue and work on other assigned issues.

**Pull request merged**
