### PR TITLE
Footer redesign

### LINKED ISSUE #4: Design a new creative footer
It will be better if you refer to some footer design of the Indian government website.

### PR DESCRIPTION
**Pull request by RiyaGupta89**
#### Issue Number
fixes #4 

#### Describe the changes you've made
Added links in the footer

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [] I have added my name in the contributors list at the end of README.md file.
- [✔️] My code follows the code style of this project.
- [✔️] My change requires a change to the documentation.
- [✔️] I have updated the documentation accordingly.
- [✔️] I have added tests to cover my changes.
- [✔️] All new and existing tests passed.
- [✔️] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 it looks more like a navbar than a footer.


Can you design something like this?
image

**Comment by QAZIMAAZARSHAD** [comment]
Okk I am accepting this PR.

If you want to improve I will open a new issue after merging this PR,

ask me to assign you if you want to work on this.

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD I would like to improve the footer.
But please specify the content like copyright etc, that will be there on footer. Can you write it here? I'll make a new footer.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I would like to improve the footer.
> But please specify the content like copyright etc, that will be there on footer. Can you write it here? I'll make a new footer.

Ping me on https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/216

**Pull request merged**
