### PR TITLE
Made Dark Mode / Theme persistent

### LINKED ISSUE #397: Dark Mode / Theme is not persistent among pages.
## Describe the bug
Dark mode / Theme is not consistent among pages. If we select dark mode on login page and go back to help page (or any other page) or even refresh the page, it loads the light theme by default.

## To Reproduce
1. Toggle Dark Mode in any page.
2. Refresh the page / go to any other page
3. Dark is not selected by default

## Expected behavior
Theme should be persistent.

### PR DESCRIPTION
**Pull request by developer-diganta**
#### Describe the changes you've made
Dark Mode / Theme has been now made persistent. If one selects dark theme , then all subsequent visits to the pages will be in dark theme unless the user changes it.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan
Test link : [https://developer-diganta.github.io/Voters-Registration-Portal/index.html](url)

#### Checklist
- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@developer-diganta your branch is 5 commits behind my branch.

image

Fetch upstream.

Then I will merge.

**Comment by developer-diganta** [comment]
@QAZIMAAZARSHAD  I have done it.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I have done it.

Check it is showing your branch is 5 commits behind my branch.
You can compare the feedback submitted page, it has not been updated in your branch.

Current - https://qazimaazarshad.github.io/Voters-Registration-Portal/feedbackformsubmitted.html
Your - https://developer-diganta.github.io/Voters-Registration-Portal/feedbackformsubmitted.html

**Comment by QAZIMAAZARSHAD** [comment]
Fetch upstream.

**Comment by developer-diganta** [comment]
image
I am new to open source. Can you explain what I had to do? I did fetch upstream and in my forked repository it is showing that the branch is even.

**Comment by developer-diganta** [comment]
I guess now it works. Can you please check it?

**Pull request merged**
