### PR TITLE
#332 flip logo solved

### PR DESCRIPTION
**Pull request by stellashank**
#### Issue Number
#332
 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by stellashank** [comment]
Filp logo solved

**Comment by QAZIMAAZARSHAD** [comment]
> 
> Filp logo solved

Doesn't look like it is solved.

**Comment by QAZIMAAZARSHAD** [comment]
Have you read my latest comments.


This ->

Screenshot (22)
Screenshot (24)


The red circle indicates the wrong output on hover.
The blue circle indicates the correct output on hover.

**Comment by QAZIMAAZARSHAD** [comment]
The help page is perfectly fine. The problem is on other pages.

Also, don't do any changes manually, fetch upstream to update your repo.

I'm closing this PR. Solve the issue then make a new PR.

**Pull request closed without merging**
