### PR TITLE
Created a Logout button on registration page.

### PR DESCRIPTION
**Pull request by pruthvirajjadhav1**
ISSUE NUMBER: #197 

#### Describe the changes you've made
I had made a button for Logout that redirects you to the login page.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD aren't we saving any session information into localstorage or cookie .

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD aren't we saving any session information into localstorage or cookie . ?

What?

Didn't get it.

**Comment by nlok5923** [comment]
i am talking about tokens like if user visit our site and already has token in it's localstorage then we can surpass the login process.

**Comment by QAZIMAAZARSHAD** [comment]
@pruthvirajjadhav1 the position of the button and color don't look nice.

image
image

In both mobile as well as desktop.

**Comment by QAZIMAAZARSHAD** [comment]
> i am talking about tokens like if user visit our site and already has token in it's localstorage then we can surpass the login process.

No, this site does not have this.

**Comment by pruthvirajjadhav1** [comment]
> @pruthvirajjadhav1 the position of the button and color don't look nice.
> 
> image
> image
> 
> In both mobile as well as desktop.

I'll work on it which specific color and position do you want me to put it on.

**Comment by QAZIMAAZARSHAD** [comment]
@pruthvirajjadhav1 change the color of the button to pink color like the scroll bar.

Shift the button in the select language and zoom button section. Rearrange them so they look good.
Check responsiveness after the changes.

**Comment by nlok5923** [comment]
@pruthvirajjadhav1 any updates ?

**Comment by pruthvirajjadhav1** [comment]
> @pruthvirajjadhav1 any updates ?

I am working on it but adjusting for desktop and mobile is difficult any suggestions from you

**Comment by nlok5923** [comment]
@pruthvirajjadhav1 can you please deploy your changes to a static site and provide me a link for the same so that i can guide you in better way .

**Comment by QAZIMAAZARSHAD** [comment]
@pruthvirajjadhav1 any updates? Or should I assign the issue to someone else?

**Comment by pruthvirajjadhav1** [comment]
> @pruthvirajjadhav1 any updates? Or should I assign the issue to someone else?

I'm extremely sorry my exams have kicked in so I'm dealing with that. So please assign it to anyone who is interested.

**Pull request closed without merging**
