### PR TITLE
Confirm Password Field Added

### LINKED ISSUE #344: Add re-enter password field in forget password page.
## Describe the bug
Currently the forget password page do not have field to confirm the new password. 

## To Reproduce
1.  headover to forget password page

## Expected behavior
There should be a confirm password field so as to make sure password is correctly entered.

## Logs
image

## Environment (please complete the following information):
 - OS: all
 - Browser: all

## Additional context
also change login button text from "login"  -> "reset"

### PR DESCRIPTION
**Pull request by Garima-7**
Fixed #344

#### Describe the changes you've made
Changed the file "forgetPass.html"
Added the Confirm Password Field to it.
Changed the text of button to reset.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Screenshot of added functionality
image

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Garima-7 you are part of LGMSoC or DCP.

**Comment by Garima-7** [comment]
> @Garima-7 you are part of LGMSoC or DCP.

DCP

**Comment by QAZIMAAZARSHAD** [comment]
@Garima-7 fill this form https://docs.google.com/forms/d/e/1FAIpQLSf5niPmalvS1rs0EOcxBOCRrHtIeNIydc9y3NOW4tI9DiTIZg/viewform.

**Comment by Garima-7** [comment]
Pls change the label to LGMSOC21.
Sorry to disturb you.

**Comment by QAZIMAAZARSHAD** [comment]
> Pls change the label to LGMSOC21.
> Sorry to disturb you.

Have you filled the above form or not?

**Comment by Garima-7** [comment]
Actually the problem is that I am enrolled with both the programs but in DCP I am enrollled in learner program and they are saying that learner can't contribute. So my points will not be counted in DCP.

**Comment by Garima-7** [comment]
> Actually the problem is that I am enrolled with both the programs but in DCP I am enrollled in learner program and they are saying that learner can't contribute. So my points will not be counted in DCP.

I have one doubt that if we are enrolled with two programs simultaneously so can we add both labels?

**Comment by QAZIMAAZARSHAD** [comment]
yes

**Comment by QAZIMAAZARSHAD** [comment]
@Garima-7 you said you are part of LGMSoC then why have you filled DCP form?

**Comment by Garima-7** [comment]
I have filled it before only when I was informed that learning program of DCP can't contribute.

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

I am deleting your responses.

**Pull request merged**
