### PR TITLE
Removed overlapping bug of dark/light toggle button of every page

### LINKED ISSUE #428: Adjust the overlapping of dark/night toggle button in mobile view
Shift the button slightly upwards so it does not overlap with the toll-free number button.

Do this on every page.

### PR DESCRIPTION
**Pull request by aasthasaxena217**
#### Fixes #428 
 
Fixed the overlapping of toggle button of every page in mobile view

you can check this here:
https://aasthasaxena217.github.io/Voters-Registration-Portal/login.html

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@aasthasaxena217 fetch upstream your repo is few commits behind.

**Comment by aasthasaxena217** [comment]
Done

**Comment by QAZIMAAZARSHAD** [comment]
All pages are fine except the help page.

**Comment by QAZIMAAZARSHAD** [comment]
> Done

Nope.

Still, 3 commits behind. Upstream this branch.

**Comment by QAZIMAAZARSHAD** [comment]
@aasthasaxena217 a little problem in form-correction page as well.

**Comment by aasthasaxena217** [comment]
Form-correction page is also updated.
Are still these are 3 commits behind, because I am not able to fetch upstream. Can you help in this.

**Comment by QAZIMAAZARSHAD** [comment]
> Form-correction page is also updated.
> Are still these are 3 commits behind, because I am not able to fetch upstream. Can you help in this.

Nope.

You made it even in this commit 

https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/pull/438/commits/4819061fefa63ebb56fa206555f22e0cb28687e0.

**Pull request merged**
