### PR TITLE
adjust zoom language button

### PR DESCRIPTION
**Pull request by nitishapiplani**
issue#77
Adjusted  zoom ,language and note field
added header to home.html

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Wrong you have also disturbed the desktop view a lot.
And the mobile view is also poor.
See ->

image

Screenshot (108)

**Comment by QAZIMAAZARSHAD** [comment]
First update your repository with the updated main repository then do the changes.

**Comment by nitishapiplani** [comment]
can you plzz tell what type of view you want on dexstop

**Comment by QAZIMAAZARSHAD** [comment]
Same view.

**Comment by QAZIMAAZARSHAD** [comment]
> Wrong you have also disturbed the desktop view a lot.
> And the mobile view is also poor.
> See ->
> 
> image
> 
> Screenshot (108)

check yourself hind and English text are written out of list.

Don't change anything in desktop view.

**Pull request closed without merging**
