### PR TITLE
Updated README.md with Screenshots for all the pages

### LINKED ISSUE #442: Update Screenshots in Readme
Add screenshots of every page.

### PR DESCRIPTION
**Pull request by ManishS6**
#### Fixes #(issue number)
Fixes #442 

#### Describe the changes you've made
The Screenshots corresponding to the Loading Screen, Login Page, Main Form along with an image of the Banner were updated in README.md under the heading 'A sneak peek into what we have here🙈'

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Deploy your changes to github page or netlify and mention deployment link:
NA

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] Open Source Program name: Hacktoberfest 2021

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@ManishS6 images are not fine.

And these are not all the screenshots.

**Comment by ManishS6** [comment]
> @ManishS6 images are not fine.
> 
> And these are not all the screenshots.

Hey can you tell me whats wrong with these images, so that I could start again.

**Comment by QAZIMAAZARSHAD** [comment]
Loading_Page
Main_Form

**Comment by QAZIMAAZARSHAD** [comment]
And remove the banner image.

Also, add screenshots of all pages.
Sign-up page
Forget Password page
Feedback page
Help page
Show one page with dark theme

**Comment by ManishS6** [comment]
@QAZIMAAZARSHAD on it.

**Pull request merged**
